var bankName ;
console.log("Bank Name is:", bankName);
var bankNameTypeOf = typeof bankName;
console.log("type of Bank Name is:",bankNameTypeOf);
bankName = "SBI Bank";
console.log("Bank name is :", bankName);
var bankNameTypeOf= typeof bankName;
console.log(" Type of Bank Name:", bankNameTypeOf );
console.log("=====================================================================");
var marks = '90%';
console.log(" MArks is:", marks);
var markTypeOF = typeof marks;
console.log("Type of Marks is:", markTypeOF);
console.log("=====================================================================");
var isWorking;
console.log("Working is:", isWorking);
var isworkingTypeOf= typeof isWorking;
console.log("Type of isWorking:",isworkingTypeOf);
isWorking= true;
console.log("Working:",isWorking);
var isWorkingTypeOf= typeof isWorking;
console.log("Type Of IsWorking:",isWorkingTypeOf);
console.log("=====================================================================");
var totalCount ="Hundred and Seven"
console.log("Total Count is:",totalCount);
var totalCountTypeOf =typeof totalCount;
console.log("Type Of Total Count is:",totalCountTypeOf);
console.log("UPDATE VALUE");
var totalCount =107;
console.log("Total Count is:",totalCount);
var totalCountTypeOf =typeof totalCountTypeOf;
console.log("Type Of Total Count is:",totalCountTypeOf);